### PR TITLE
Added a new map for Alexandria

### PR DESCRIPTION
**Pull request by aemaddin**
Dear Mr Adam,

Kindly find the new map hosted on `https://medliq-alexandria.com`. Unfortunately, I am not working with angular, so if there are any issues related to my request, please guide me throw how to add this map to your project.

Thanks

### CODE REVIEW

**Comment by akariv** [comment]
Hey @aemaddin - this looks great! 
Which platform did you use for developing the website?
Can it be exported as a static site, or is it based on some sort of CMS?

Thanks!

**Comment by aemaddin** [comment]
Hi @akariv

We are using Vuejs and Vanilla js, and we are already planning to convert the website to Angularjs to inject our code into your wonderful project, but it will take time to do that because we didn't work with Angularjs in the meantime.

**Comment by akariv** [comment]
Working with Angular is not a requirement :) !

We can add other, static sites under the 'external' directory:
https://github.com/akariv/atlas-medliq/tree/master/external

(see the 'species-map' there).

If you want, you can add your code (after build) there and I will connect
it to the website.

**Comment by aemaddin** [comment]
Great,

But also, the project was initiated as a PHP (Laravel) project, and it uses a bit different approach to building the project, so it will take time to extract the project to use only Vuejs. So, could we add this external link to `https://medliq-alexandria.com`? After that, we can work on extracting the code and host it totally on your project.

**Comment by akariv** [comment]
@aemaddin Sure, so let's create a minimal page which uses an iframe to show the website hosted by you.
This minimal page can then be put in the external directory.
Sound good?

**Comment by aemaddin** [comment]
@akariv, yes, thanks. I will send a new PR asap.

**Comment by aemaddin** [comment]
@akariv thank you for your support. Please check and tell me if there are any issues needed to fix.

**Comment by aemaddin** [comment]
Hi @akariv,

Is PR need any modifications?

**Comment by akariv** [comment]
Hey @aemaddin - this looks good but there's still some work to do 😄 

Please see this index.html file: https://github.com/akariv/atlas-medliq/blob/master/src/index.html

Take all the meta-tags (the ones in the `head` section) and add them to your index.html file.
Update the parts that are templated with the text from the `social-m7.json` file (and then remove it, as it's not needed here).

Thank you!

**Comment by aemaddin** [comment]
@akariv, kindly find the changes.

**Comment by akariv** [comment]
Sure, so let's create a minimal page which uses an iframe to show the
website hosted by you.
This minimal page can then be put in the external directory.
Sound good?

**Comment by aemaddin** [comment]
@akariv, it's already done

You can find index.html has an iframe tag with the hosted project.

**Comment by akariv** [comment]
@aemaddin I merged this pull request, thank you.
I created an issue with some follow-up tasks:

https://github.com/akariv/atlas-medliq/issues/3

Thanks!

**Pull request merged**
